hub_col_list = ['REVENUE_ID',
 'Year',
 'Month',
 'Local Client ID',
 'Duration Code',
 'Company Number',
 'Product Line Name',
 'Product Line Code',
 'Product Group Name',
 'Product Group Code',
 'Product SubGroup Name',
 'Product SubGroup Code',
 'Production Code',
 'Level 3 Code',
 'Level 2 Code',
 'Bill Type Code',
 'Local Client Name',
 'Reporting Country Code',
 'Revenue in Local Currency',
 'Local Revenue Department',
 'RC Department Name',
 'RC_DEPT',
 'Entry Mode',
 'Basis Code',
 'Accrual Indicator - US only',
 'Invoice Date',
 'Bill Efective Date',
 'Coverage Effective Date',
 'Coverage Expiration Date',
 'Level 1 Country Code',
 'Level 4 Product Code']

spoke_col_list =['L4. Planning Product: Model',
 'L4. Planning Product: Planning Year',
 'L4. Planning Product: Country Code',
 'L4. Planning Product: Client Code',
 'L4. Planning Product: Department Code',
 'L4. Planning Product: Product Code',
 'Time',
 'Accounts L4: CSR Accounts',
 'Revenue Master Actuals',
 'FID System Actuals',
 'Manual Adjustments',
 'Restatements',
 'Projection',
 'NR Override',
 'NR Override Offset',
 'Final Values']