dict_of_etl = {
    "zones_etl_params": {
        "zones_df": ("Name", "Level 11"),
        "spoke_df": ("L4. Planning Product: Department Code", "L4. Planning Product: RC Country Level 1"),
        "extra_zones_df": ("RC#", "Zone"),
    },
    "zones_to_ignore": [
        "Consulting Solutions",
        "Mexico - Country level 1",
        "MMA Southwest - Country level 1",
        "Private Client Services - Country level 1",
        "SA Multinational",
        "US and Canada Captives Total - Country level 1",
        "blank",
    ],
    "client_names_to_ignore": [
        "ACS EB Direct Bill",
        "ACS Personal Lines",
        "Company Number Not Available",
        "Corporate Fit To Size - Centra",
        "Corporate Fit To Size - Northe",
        "Corporate Fit To Size - South",
        "Corporate Fit To Size - Southe",
        "Corporate Fit To Size - West",
        "Corporate Fit To Size-Florida",
        "Cyber MRC - Columbia",
        "Marsh ACS/EBS individual Medic",
        "Non Disclosure Marsh Space Pro",
        "PEMA US Projects",
        "Renewables Corporate - Central",
        "Renewables Corporate - Florida",
        "Renewables Corporate - West",
        "Renewables Corporate-Northeast",
        "Renewables Corporate-South Cen",
        "Renewables Corporate-Southeast",
        "Renewables Risk Mgt - Central",
        "Renewables Risk Mgt - Northeas",
        "Renewables Risk Mgt - Southeas",
        "Renewables Risk Mgt - West",
        "Renewables Risk Mgt-South Cent",
        "Wortham Dallas  Corporate",
        "Wortham Ft. Worth  Corporate",
        "Wortham Ft. Worth - RM",
        "Wortham Houston  Corporate",
        "Wortham San Antonio  Corporat",
    ],
    "col_rename_dict": {
        "revenue_id": "revenue_id",
        "year": "year",
        "month": "month",
        "local client id": "client_number",
        "duration code": "duration_cd",
        "company number": "company_number",
        "product line name": "product_line_nm",
        "product line code": "product_line_cd",
        "product group name": "product_group_nm",
        "product group code": "product_group_cd",
        "product subgroup name": "product_subgroup_nm",
        "product subgroup code": "product_subgroup_cd",
        "production code": "production_code",
        "level 3 code": "client_number1",
        "level 2 code": "client_numberO",
        "bill type code": "billing_type",
        "local client name": "client_nm",
        "reporting country code": "country_cd",
        "revenue in local currency": "net_revenue",
        "local revenue department": "fcs_department_nr",
        "rc department name": "fcs_department_nm",
        "rc_dept": "fcs_department_cd",
        "entry mode": "entry_mode",
        "basis code": "basis_code",
        "accrual indicator - us only": "accrual_type_us",
        "invoice date": "invoice_date",
        "bill efective date": "bill_effective_dt",
        "coverage effective date": "cv_effective_dt",
        "coverage expiration date": "cv_expiration_dt",
        "level 1 country code": "country_cd_l1",
        "level 4 product code": "product_cd_l4",
        "non_recurring_flag": "non_recurring_flag",
        "mi_lookup_level4": "mi_lookup_level4",
        "final_mip_desc": "final_mip_desc",
        "market_segment": "market_segment",
    },
    "cols_to_keep": [
        "year",
        "month",
        "client_number",
        "duration_cd",
        "product_line_nm",
        "production_code",
        "billing_type",
        "net_revenue",
        "entry_mode",
        "basis_code",
        "accrual_type_us",
        "invoice_date",
        "bill_effective_dt",
        "cv_effective_dt",
        "cv_expiration_dt",
        "non_recurring_flag",
        "mi_lookup_level4",
        "final_mip_desc",
        "market_segment",
    ],
    "col_order": [
        "client_number",
        "product_subgroup_nm",
        "year",
        "month",
        "product_group_nm",
        "product_line_nm",
        "company_name",
        "mi_lookup_level4",
        "net_revenue",
        "final_mip_desc",
        "market_segment",
        "fcs_department_nr",
        "duration",
        "product_subgroup_cd",
        "product_line_cd",
        "country_cd",
    ],
    "month_dict_for_date_range": {
        "01": "jan",
        "02": "feb",
        "03": "mar",
        "04": "apr",
        "05": "may",
        "06": "jun",
        "07": "jul",
        "08": "aug",
        "09": "sep",
        "10": "oct",
        "11": "nov",
        "12": "dec",
    },
    "zonesana": [
        "Central Zone",
        "Northeast Zone",
        "West Zone",
        "Southeast Zone",
        "ACS",
        "Florida Zone",
        "East Zone"
    ],
    "zonesrm": [
        "MAR_U.S. BROKERAGE - NORTHEAST",
        "MAR_U.S. BROKERAGE - SOUTHEAST",
        "MAR_U.S. BROKERAGE - CENTRAL",
        "MAR_U.S. BROKERAGE - WEST",
        "MAR_U.S. BROKERAGE - FLORIDA",
        "MAR_CENTRAL ZONE",
        "MAR_WEST ZONE",
        "MAR_SOUTHEAST ZONE",
        "MAR_NORTHEAST ZONE",
        "MAR_FLORIDA ZONE",
        "US TOTAL OTHER",
        "U.S. TOTAL OTHER",
    ],
    "key_cols": [
        "client_number",
        "product_subgroup_nm",
        "year",
        "month",
    ],
    "product_cols_for_process": [
        "client_number",
        "product_line_nm",
    ],
    "segment_cols_for_process": [
        "client_number",
        "product_line_nm",
        "product_group_nm",
        "non_recurring",
        "is_bermuda",
    ],
    "name_cols_for_process": [
        "client_number",
        "product_line_nm",
    ],
    "industry_cols_for_process": [
        "client_number",
        "product_line_nm",
        "product_group_nm",
        "non_recurring",
        "is_bermuda",
    ],
    "cols_for_table": ["client_number", "product_line_nm", "product_group_nm", "non_recurring", "is_bermuda"],
    "month_dict_for_table": {
        "1": "Jan_revenue",
        "2": "Feb_revenue",
        "3": "Mar_revenue",
        "4": "Apr_revenue",
        "5": "May_revenue",
        "6": "Jun_revenue",
        "7": "Jul_revenue",
        "8": "Aug_revenue",
        "9": "Sep_revenue",
        "10": "Oct_revenue",
        "11": "Nov_revenue",
        "12": "Dec_revenue",
    },
    "cols_for_dept_ana": ["client_number", "product_line_nm", "product_group_nm"],
    "depts_to_remove": [
        [
            "D_BM0023",
            "D_US001T",
            "D_US0026",
            "D_US002T",
            "D_US0031",
            "D_US0036",
            "D_US003T",
            "D_US0043",
            "D_US004T",
            "D_US0056",
            "D_US005T",
            "D_US0060",
            "D_US0062",
            "D_US0065",
            "D_US0068",
            "D_US006T",
            "D_US0072",
            "D_US0077",
            "D_US007T",
            "D_US008T",
            "D_US0098",
            "D_US0099",
            "D_US009T",
            "D_US010T",
            "D_US022U",
            "D_US031U",
            "D_US0335",
            "D_US0348",
            "D_US0368",
            "D_US03AW",
            "D_US0403",
            "D_US0409",
            "D_US0412",
            "D_US0415",
            "D_US0431",
            "D_US0464",
            "D_US0546",
            "D_US055P",
            "D_US0574",
            "D_US0644",
            "D_US0647",
            "D_US0650",
            "D_US0692",
            "D_US0697",
            "D_US0699",
            "D_US0739",
            "D_US0792",
            "D_US0842",
            "D_US0858",
            "D_US0896",
            "D_US0917",
            "D_US0920",
            "D_US0946",
            "D_US0971",
            "D_US0988",
            "D_US1027",
            "D_US10AN",
            "D_US1132",
            "D_US1133",
            "D_US1147",
            "D_US1167",
            "D_US1168",
            "D_US1174",
            "D_US1176",
            "D_US1185",
            "D_US1186",
            "D_US1187",
            "D_US1188",
            "D_US11AN",
            "D_US1203",
            "D_US1239",
            "D_US12AN",
            "D_US1331",
            "D_US1412",
            "D_US1459",
            "D_US14BC",
            "D_US1546",
            "D_US158A",
            "D_US158W",
            "D_US1632",
            "D_US1661",
            "D_US1672",
            "D_US1724",
            "D_US1726",
            "D_US172T",
            "D_US1736",
            "D_US1737",
            "D_US1769",
            "D_US1770",
            "D_US1774",
            "D_US1783",
            "D_US1846",
            "D_US1849",
            "D_US1873",
            "D_US1923",
            "D_US1975",
            "D_US2116",
            "D_US2180",
            "D_US2204",
            "D_US2279",
            "D_US2308",
            "D_US2362",
            "D_US2365",
            "D_US2375",
            "D_US2379",
            "D_US2419",
            "D_US2477",
            "D_US24BG",
            "D_US2624",
            "D_US2628",
            "D_US2686",
            "D_US2751",
            "D_US2777",
            "D_US2779",
            "D_US2780",
            "D_US2782",
            "D_US2787",
            "D_US2788",
            "D_US2791",
            "D_US307Y",
            "D_US3554",
            "D_US3868",
            "D_US4227",
            "D_US493B",
            "D_US497B",
            "D_US49AU",
            "D_US5088",
            "D_US50AU",
            "D_US609A",
            "D_US69AP",
            "D_US930P",
            "D_US931P",
            "D_US932P",
            "D_US933P",
        ]
    ],
}
