version: "3.10"
 
services:
  api-dev-svc:
    build:
      context: ./api
      dockerfile: api.local.Dockerfile
    env_file:
      - .env
    depends_on:
      - redis-dev-svc
    # mem_limit: 1g  # Set the memory limit to 1 GB
    # cpus: 1.5
    deploy:
      replicas: 2
 
  etl-dev-svc:
    build:
      context: ./workflows
      dockerfile: dagster.Dockerfile
    ports:
      - "3030:3030"
    env_file:
      - .env
    depends_on:
      - api-dev-svc
      - redis-dev-svc
 
  redis-dev-svc:
    image: redis:alpine
    ports:
      - "6379:6379"
    # cpus: 2
    # mem_limit: 2g
 
  celery-dev-svc:
    build: 
      context: ./api
      dockerfile: api.local.Dockerfile  # Use the same build context as your FastAPI app
    command: celery -A main.celery_app worker --loglevel=info #--concurrency=5 # Command to run the Celery worker
    deploy:
      replicas: 6
      resources:
        limits:
          cpus: '2'
          memory: 2g
    env_file:
      - .env
    depends_on:
      - redis-dev-svc